export { default as Home } from './Home';
export { default as Shop } from './Shop';
export { default as ProductDetails } from './ProductDetails';
export { default as Blog } from './Blog';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Cart } from './Cart';
export { default as Checkout } from './Checkout';
export { default as NotFound } from './NotFound';
